name: Scala CI

on:
  push:
    branches:
      - '**'          # Triggers on all branches
  pull_request:
    branches:
      - master        # PRs only trigger when affecting master

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: apt-get update
        run: sudo apt-get update

      - name: Setup GCC
        run: sudo apt-get install -y gcc-riscv64-unknown-elf

      - name: Run tests
        run: make test

      - name: Check test result
        id: test_result
        run: |
          if [[ $? -eq 0 ]]; then
            echo "Tests passed."
            echo "##vso[task.setvariable variable=test_outcome;isSuccess=true]"
          else
            echo "Tests failed."
            echo "##vso[task.setvariable variable=test_outcome;isSuccess=false]"
          fi

      - name: Create quarantine branch on test failure
        if: steps.test_result.outputs.test_outcome == 'false'
        run: |
          # Get the latest commit hash of master
          git fetch origin master
          latest_commit=$(git log origin/master -1 --pretty=format:"%H")
          
          # Checkout a new quarantined branch
          git checkout -b quarantine/WAAAlex1-${GITHUB_RUN_ID}
          
          # Make sure there's a unique commit (empty commit)
          git commit --allow-empty -m "Initial quarantine commit after failed tests"
          
          # Push the quarantined branch to remote
          git push origin quarantine/WAAAlex1-${GITHUB_RUN_ID}
          
          # Create a pull request
          gh pr create --base master --head quarantine/WAAAlex1-${GITHUB_RUN_ID} --title "Quarantine Branch for WAAAlex1-${GITHUB_RUN_ID}" --body "This PR contains changes from the quarantined branch for manual review."