name: Scala CI (Pull Request)

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: apt-get update
        run: sudo apt-get update

      - name: Setup GCC
        run: sudo apt-get install -y gcc-riscv64-unknown-elf

      - name: Run tests
        id: run_tests
        run: |
          echo "Running tests..."
          set +e
          make test
          echo "TEST_EXIT_CODE=$?" >> $GITHUB_ENV
          set -e

      - name: Fail job if tests failed
        if: env.TEST_EXIT_CODE != '0'
        run: exit 1

      - name: Comment on failure
        if: env.TEST_EXIT_CODE != '0'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = await core.getOutput('run_tests');
            const testResult = process.env.TEST_EXIT_CODE;
            console.log(`Test Result: ${testResult}`);
            console.log(`Output: ${output}`);
            if (testResult !== '0') {
              const message = `
                Scala CI failed! Tests did not pass.
                <details><summary>Test Output</summary>
                \`\`\`
                ${process.env.TEST_EXIT_CODE}
                \`\`\`
                </details>
              `;
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }